<a href="https://colab.research.google.com/github/mariaeduardasouzabranco/AulaGitHub/blob/main/aula3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#importar a biblioteca NumPy
#atribuir um apelido a importação
import numpy as np

#criar uma array com notas de alunos
notas = np.array([7.5,8.0,6.5,9.0,5.5])

#exibir o conteúdo do array
print(notas)

[7.5 8.  6.5 9.  5.5]


In [5]:
#exibir o primeiro elemento do array
print(notas[0])

#exibir o segundo elemento do array
print(notas[1])

#exibir o ultimo elemento do array
print(notas[-1])

7.5
8.0
5.5


In [8]:
#exibir a maior nota
print("Maior nota: ", notas.max())

#exibir a menor nota
print("Menor nota: ", notas.min())

#exibir a media de notas
print("Media notas: ", notas.mean())

#exibir a soma total das notas
print("Soma notas: ", notas.sum())

Maior nota:  9.0
Menor nota:  5.5
Media notas:  7.3
Soma notas:  36.5


In [10]:
#multiplicação de valores

print(notas * 2)

#calcular um desconto das notas
print (notas * 0.9)

[15. 16. 13. 18. 11.]
[6.75 7.2  5.85 8.1  4.95]


In [14]:
#criar um array
idades = np.array([15,16,18,21,30,17,45])

#verificar quais idades sao maiores ou iguais a 18 anos
print(idades >= 18)

#filtrar as idades >= 18
print(idades[idades >= 18])
print(np.where(idades >= 18))
index = np.where(idades >= 18)
print(idades[index])

#ordenar o array
print(np.sort(idades)) #crescente
print(np.sort(idades)[::1]) #decrescente

[False False  True  True  True False  True]
[18 21 30 45]
(array([2, 3, 4, 6]),)
[18 21 30 45]
[15 16 17 18 21 30 45]
[15 16 17 18 21 30 45]
